### ISSUE TITLE
Menüleiste

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#10]
@Theuniquereal hat da einen Plan...

**Comment by Denormos** [comment]
Du hast dein Ziel nicht erreicht

**Comment by LukasGasp** [comment]
> Du hast dein Ziel nicht erreicht

Doch. Er hat die Menüleiste fertig. Jedoch dabei all meinen Content entfernt. Daher noch kein Release

**Comment by LukasGasp** [comment]
Luan hat aufgegeben
