### ISSUE TITLE
Discover nicht zentral 

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#100]
@Denormos...

![Screenshot_20220511_165132_de.lukasgasp.klosterguide.knechtsteden_klosterguide_v1.jpg](https://user-images.githubusercontent.com/72341833/167883298-48449638-39e2-49eb-9de8-34cd70418053.jpg)

**Comment by Denormos** [comment]
@LukasGasp auf Ipad testen
