### ISSUE TITLE
Durchsichtige Map icons

### ISSUE THREAD

**Issue by Denormos** [LukasGasp/klosterguide#18]
Hey Lukas (und Luan sry) ganz interessant hier würde vorschlagen das die Map Icons die gerade nicht angeklickt sind leicht durchsichtig im Hintergrund sichtbar sind. Boa und mir fällt gerade noch was ein wie wäre es wenn die nächste Station am sichtbarsten ist(höchste opacity sagen wir Mal bei 30%) die übernächste bei 20% und die die danach folgen 10%

**Comment by Denormos** [comment]
Hey wie füge ich Labels hinzu

**Comment by LukasGasp** [comment]
> Hey wie füge ich Labels hinzu

Bist du im Web oder App?

**Comment by Denormos** [comment]
> 

Web

**Comment by LukasGasp** [comment]
> Web

Kann ich dir morgen zeigen. Eigentlich in der Bar rechts. Eventuell reichen die Berechtigungen noch nicht.

**Comment by LukasGasp** [comment]
Habe es ausprobiert. Sieht im Endeffekt beim anzeigen aller Stationen schlecht aus. Während der Navigation selbst verwirrt es mehr, als es hilft. (Man muss wird während der Tour teilweise hin und wieder zurück geschickt...)
