### ISSUE TITLE
Start Navigation

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#22]
Zwei Knöpfe sind tatsächlich kein schöner Start einer Tour

**Comment by Denormos** [comment]
@Theuniquereal wie läufts damit

**Comment by Theuniquereal** [comment]
Gut Versuche aber beim gleichen Design wie bei den anderen Seiten zu bleiben

**Comment by LukasGasp** [comment]
Durch 6634f4de1224ba6f09dc909e3d6c9b96ea9f05e2 hinzugefügt
