### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#23]
Ein schwarzes durchsichtiges Icon ist schlecht. (Mit einem schwarzen Hintergrund unsichtbar)

**Comment by Denormos** [comment]
Außerdem ist das Icon wenn ich die App starte hellgrün und in den Tabs braun

**Comment by Denormos** [comment]
Ist jetzt nicht mehr durchsichtig, hat aber bei mir immernoch braunen Hintergrund. Splash screen ist jetzt weiss

**Comment by Denormos** [comment]
![Screenshot_20211204-203322](https://user-images.githubusercontent.com/95382828/144725977-6cbfc02f-5a53-4188-a736-afca95fd9190.png)

**Comment by Denormos** [comment]
![Screenshot_20211204-230200](https://user-images.githubusercontent.com/95382828/144725991-f4800ea1-fd7f-42c6-b199-10b511d08687.png)
