### ISSUE TITLE
Motorola Multitasking Icon

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#29]
Denormos Handy zeigt falsches App Icon in Multitasking View
![WhatsApp Image 2021-12-04 at 23 57 49](https://user-images.githubusercontent.com/72341833/144727246-d0138089-d6ff-4ecf-9f3f-09df6ca98306.jpeg)

**Comment by Denormos** [comment]
Also um ehrlich zu sein habe ich keine Idee wie man das lösen soll

**Comment by LukasGasp** [comment]
> Also um ehrlich zu sein habe ich keine Idee wie man das lösen soll

Du hast online gesucht, oder? Auch im allgemeinen Zusammenhang mit Android und Motora

**Comment by LukasGasp** [comment]
@Denormos Hast du das probiert: 
[https://stackoverflow.com/questions/32522600/android-app-icon-not-showing-in-running-apps?rq=1](url)

**Comment by Denormos** [comment]
ist ja nur bei motorola + ist nicht in flutter

**Comment by LukasGasp** [comment]
Flutter baut quasi nur das Android skript. Wenn du in den Ordner Android gehst findest du das gesammte Ding. Beispielsweise die AndroidManifest Datei wird nicht überschrieben...

**Comment by Denormos** [comment]
habe nichts gemacht klappt jetzt trotzdem
