### ISSUE TITLE
Stationen hinzufügen

### ISSUE THREAD

**Issue by Denormos** [LukasGasp/klosterguide#32]
Die ganzen neuen Stationen machen

**Comment by LukasGasp** [comment]
Waiting for Word Version by Maric...

**Comment by LukasGasp** [comment]
Hier die Datei:

[Schlussfassung STATIONSTEXTE.docx](https://github.com/LukasGasp/klosterguide/files/7714247/Schlussfassung.STATIONSTEXTE.docx)

Werde anfangen und den Commit machen, wenn ich keine Lust mehr habe.

**Comment by Denormos** [comment]
super
