### ISSUE TITLE
Endkarte

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#38]
Wie im Word-Dokument zu sehen ist, soll es eine Endstation geben. Text: 

> Abschied // Feedback // Spenden
 Zum Abschluss möchten wir uns bedanken, dass Sie unsere Klosterführer-App benutzt haben. Wir hoffen nicht nur, Ihnen Knechtsteden informationsreich vorgestellt zu haben. Auch würde es uns freuen, wenn Sie die Führung genossen und unsere App sowie Knechtsteden als sehenswürdigen Ort weiterempfehlen können. 
Vielleicht sitzen Sie ja gerade im Klosterhof und warten auf Ihre Bestellung. Wir wären Ihnen sehr verbunden, wenn Sie uns ein Feedback gäben. Klicken Sie nach Ablauf dieser Wiedergabe einfach auf untenstehenden Button und teilen Sie uns gern Ihre Meinung mit. Vielleicht fehlt ja auch eine Information, über die Sie gern Bescheid wüssten. Helfen Sie uns, unsere App stetig weiterzuentwickeln.
Eine letzte Kleinigkeit in eigener Sache: Ob Stiftung Alberts von Aachen oder Förderung durch Anton Scheben – Knechtsteden lebte und überlebte immer durch die großzügigen Spenden derer, die Knechtsteden als besonderen Ort erkannt haben. Wie eben bereits erwähnt wurde, trafen sich die Förderer Knechtstedens gerade an diesem Ort. Vielleicht möchten auch Sie unseren besonderen Ort fördern. Dabei steht es Ihnen natürlich frei, ob Sie das Missionshaus der Spiritaner oder unsere Schule unterstützen möchten. Klicken Sie einfach auf einen der untenstehenden Buttons zur Spende. Haben Sie vielen Dank und kommen Sie bald wieder! 
 Übrigens: In Knechtsteden können Sie ganz hervorragend spazieren gehen. Oder Sie kommen einmal mit dem Rad vorbei. Einige Routenvorschläge finden Sie auf der Tafel gegenüber des Klosterhofs. Wir wünschen Ihnen alles Gute! Auf Wiedersehen! 
[Button: „Feedback und Kontakt“]
[Button: „Spende für das Missionshaus“]
[Button: „Spende für das Norbert-Gymnasium“]
[Button: „Beende die Führung“]

**Comment by Denormos** [comment]
Das ist doch einfach ein Screen der nach der letzten Station erscheint

**Comment by LukasGasp** [comment]
> Das ist doch einfach ein Screen der nach der letzten Station erscheint

Ja. Eine Station die aber speziell ist, weil sie unten spezielle Knöpfe hat
