### ISSUE TITLE
Stationen zurück-Button

### ISSUE THREAD

**Issue by Denormos** [LukasGasp/klosterguide#41]
Man sollte in der Führung auch zurück klicken können

**Comment by LukasGasp** [comment]
Jap. 
Hatte Probleme einen Zurück Knopf zu bauen. Ein floating Action button (wie der weiter Knopf) geht nicht mehr einfach, da dieser Parameter schon von weiter genutzt wird. 
Habe anschließend versucht oben einen zu implementieren. Der war nicht Klickbar. 
Muss aber auf jeden Fall gemacht werden.
