### ISSUE TITLE
Discovery design

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#56]
@Denormos Änderungen rückgängig machen. 
Namen bei allen Handys (außer seinem) nicht mehr richtig angezeigt.

**Comment by Denormos** [comment]
bei mir läufts super

**Comment by LukasGasp** [comment]
Denormos: 
Entfernt das anpassen der Größe. 

Auch Denormos: 
Wundert sich, warum die Größe nur noch auf seinem Bildschirm richtig ist.
