### ISSUE TITLE
Schlechte Formatierung 

### ISSUE THREAD

**Issue by LukasGasp** [LukasGasp/klosterguide#94]
![Screenshot_20220503_220929_de.lukasgasp.klosterguide.knechtsteden_klosterguide_v1.jpg](https://user-images.githubusercontent.com/72341833/166557854-81a5671e-f8f1-4b33-b056-30ee8606d371.jpg)

**Comment by LukasGasp** [comment]
@Denormos Kannst du das machen?

**Comment by Denormos** [comment]
@LukasGasp War die Zahl da nicht mal höher die guckt aus der Karte raus

**Comment by LukasGasp** [comment]
> @LukasGasp War die Zahl da nicht mal höher die guckt aus der Karte raus

Ah Shit. Wann haben wir den Bug erzeugt?

**Comment by LukasGasp** [comment]
Die Zahlen buggen überall. Die Zeilen nur bei langen Stationen

**Comment by Denormos** [comment]
Nur du hast den Bug
