### ISSUE TITLE
Karte Stationen Button rechts entfernen

### ISSUE THREAD

**Issue by Denormos** [LukasGasp/klosterguide#98]
Wenn du auf map gehst und dann auf eine Station gehst dann ist da unten rechts ein Button der zu noch einer map führst und wenn du dann zurück gehst kommst du auf die detailpage und wenn man dann wieder zurück geht kommt man auf noch eine map das ist schlechtes  Design wieso will man die Karte zwei mal sehen um nur eine Station auf der Karte zu haben oder wieso

**Comment by Denormos** [comment]
@LukasGasp hast du implementiert ist das bug oder feature

**Comment by LukasGasp** [comment]
Das kommt aus der Discovery Page.

Die detailpage erkennt, dass sie alleine ist. Daher könntest du eine Navigation zu ihr wollen...

**Comment by Denormos** [comment]
Ja OK dann ist das ein feature
